services:
  calibre-web-automated-book-downloader-dev:
    extends:
      file: ./docker-compose.yml
      service: calibre-web-automated-book-downloader
    build:
      context: .
      dockerfile: Dockerfile
      target: cwa-bd
    environment:
      LOG_LEVEL: debug
      FLASK_DEBUG: true
      APP_ENV: dev
     # USE_DOH: true
     # CUSTOM_DNS: cloudflare

