services:
  calibre-web-automated-book-downloader-tor-dev:
    extends:
      file: ./docker-compose.tor.yml
      service: calibre-web-automated-book-downloader-tor
    build:
      context: .
      dockerfile: Dockerfile
      target: cwa-bd-tor
    environment:
      LOG_LEVEL: debug
      FLASK_DEBUG: true
      APP_ENV: dev